{{- if .Values.app.db.local -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}-db
spec:
  ports:
    - port: {{ .Values.app.db.port }}
  selector:
    app: {{ include "service.name" . }}-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.name" . }}-db
spec:
  selector:
    matchLabels:
      app: {{ include "service.name" . }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "service.name" . }}-db
    spec:
      containers:
        - image: mysql:8.1
          name: {{ include "service.name" . }}-db
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.app.db.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.app.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.app.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.app.db.password }}
          ports:
            - containerPort: {{ .Values.app.db.port }}
              name: {{ include "service.name" . }}-db
          imagePullPolicy: "Always"
          volumeMounts:
            - name: {{ include "service.name" . }}-db-persistent-storage
              mountPath: /var/lib/user-db
      volumes:
        - name: {{ include "service.name" . }}-db-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "service.name" . }}-db-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "service.name" . }}-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "service.name" . }}-db-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{- end }}
