spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: ${DATABASE_INITIALIZATION_MODE}
    connectionProperties: useUnicode=true;characterEncoding=utf-8;useSSL=false;serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${SERVER_PORT}
