
replicaCount: 1

image:
  repository: "to be overridden"
  tag: "to be overridden"
  pullPolicy: Always

imagePullSecrets: "to be overridden"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  annotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: "to be overridden"
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

app:
  db:
    local: "to be overridden"
    host: "to be overridden"
    port: "3306"
    name: "user"
    user: "user"
    password: "to be overridden"
    initialisationMode: "always"
  server:
    port: "8080"
