name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Set up Java and Build with Gradle (Test)
        run: |
          wget https://corretto.aws/downloads/latest/amazon-corretto-20-x64-linux-jdk.deb
          sudo dpkg -i amazon-corretto-20-x64-linux-jdk.deb
          export JAVA_HOME=/usr/lib/jvm/java-20-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
          ./gradlew build

      - name: Bump version and push GitHub tag (Release version)
        id: tagger
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::881387567440:role/github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build Image and Push to ECR
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-20-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
          ./rebuildAndPush.sh -r ${{ steps.login-ecr.outputs.registry }} \
            -n apps-template -v "${{ steps.tagger.outputs.new_tag }}"

