name: Continuous Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Set up Java and Build with Gradle
        run: |
          wget https://corretto.aws/downloads/latest/amazon-corretto-20-x64-linux-jdk.deb
          sudo dpkg -i amazon-corretto-20-x64-linux-jdk.deb
          export JAVA_HOME=/usr/lib/jvm/java-20-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
          ./gradlew build

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
